### PR TITLE
issue #92 - undefined method 'helper' for ActionController::API:Class

### PR DESCRIPTION
**Pull request by gil27**
Guys, since PR #77 didn't ship it. I just added an if statement to solve it.  Simple and clear.
It solves #92

### CODE REVIEW

**Comment by weppos** [comment]
#77 is not shipped because, like this PR, it did not include any test and I don't have a way to validate it as right now I'm not using Rails 5 yet.

I am not inclined to merge this PR either, because it doesn't include any test. I will likely merge #77, when the PR will provide relevant unit tests to validate the change.

**Comment by gil27** [comment]
@weppos, please help me out with the tests.

If I add a controller that extends the API instead of Base. `ActionController::API` It would break the tests, because ActionController::API does not respond to heler, helper_method and layout method. This is the current scenario.

What kinda of tests do you think would fit this scenario?

**Comment by jcoyne** [comment]
How is it that the current Appraisal tests are passing?  It doesn't seem like they should be able to pass with this bug (which I also see)

**Comment by jcoyne** [comment]
This problem is odd. It appears that `BreadcrumbsOnRails::ActionController` is included on both `ActionController::Base` and `ActionController::API`, and the later is where it fails.

**Comment by jcoyne** [comment]
Here's where rails calls that hook with `ActionController::API`

https://github.com/rails/rails/blob/b326e82dc012d81e9698cb1f402502af1788c1e9/actionpack/lib/action_controller/api.rb#L145

I think that Appraisal is mocking too much of the rails stack and we probably need to use something like https://rubygems.org/gems/engine_cart to do proper end-to-end testing.

**Comment by jcoyne** [comment]
Okay, here's a test that this pull request will fix: https://github.com/weppos/breadcrumbs_on_rails/pull/94

**Comment by owen2345** [comment]
It works well, please accept and publish a new gem version.
Regards!

**Pull request closed without merging**
