### PR TITLE
Add the log directory to the gitignore

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by weppos** [comment]
Please explain the reason of this commit

**Comment by jcoyne** [comment]
When you run the tests it creates a `log/test.log` file.  We don't want these getting into the repository. It's akin to this file in rails itself: https://github.com/rails/rails/blob/master/railties/.gitignore

**Comment by weppos** [comment]
@jcoyne this is odd, I doesn't add any folder to me. Can you tell me which command you use to run the tests?

**Comment by jcoyne** [comment]
Yeah, I don't know what I was doing before. I can't duplicate it now.

**Pull request closed without merging**
