### PR TITLE
Add ability to pass html options by default

### PR DESCRIPTION
**Pull request by siassaj**
It's gooda

### CODE REVIEW

**Comment by weppos** [comment]
You can accomplish such behavior by creating a custom builder.

**Comment by siassaj** [comment]
obviously, this is not a feature that would be nearly ubiquitously desired or even useful in a base class.

**Comment by snowmoonsoftware** [comment]
@siassaj twitter-bootstrap has breadcrumb functionality; I've switched to that.

**Comment by siassaj** [comment]
@snowmoonsoftware  Have to use foundation, need a simple breadcrumb library which this is. But thank you for telling me, useful to know

**Pull request closed without merging**
